fetch_data: # parameters for fetch_data.py
  METADATA_FILEPATH: "../data/raw/metadata.csv"
  FINANCIAL_DATA_FILEPATH: "../data/raw/data.pkl"
  PORTFOLIO_DATA_FILEPATH: "../data/raw/portfolio.pkl"
  PERIOD: "5y"  # Grab data for the last 5 years
  INTERVAL: "1d"  # Grab daily data

create_portfolio: # configuration for create_portfolio.py
  DATA_FILEPATH: "../data/raw/data.pkl"
  PORTFOLIO_DATA_FILEPATH: "../data/raw/portfolio.pkl"
  METADATA_FILEPATH: "../data/raw/metadata.csv"
  RESULTS_BASE_DIR: "../data/results"

  # Parameters
  NUM_DAYS_TIME_HORIZON: 180
  ANALYSIS_COLUMN: "Adj Close"
  INVESTMENT_AMOUNT: 1000.  # [$]
  PORTFOLIO_VOLATILITY: 0.06
  SPARSITY_IMPORTANCE: 0.0
  TAX_RATE: 0.0
  MAX_PORTFOLIO_WEIGHT: 1.0
  DISABLE_SELLING: false
  SELL_ONLY_LOSERS: false
  ACTIVE_ASSETS: # only the following assets will be active.
    - "XXX"
    - "YYY"
    - "ZZZ"

  # Plotting
  PRICE_LIMITS: [0.6, 1.4]
  NUM_DAYS_IN_FUTURE: 30
  EXCEEDANCE_PROBABILITY: 0.95