fetch_data: # parameters for fetch_data.py
  METADATA_FILEPATH: "../data/raw/metadata.csv"
  OUTPUT_FILEPATH: "../data/raw/data.pkl"
  PERIOD: "5y"  # Grab data for the last 5 years
  INTERVAL: "1d"  # Grab daily data

create_portfolio: # configuration for create_portfolio.py
  DATA_FILEPATH: "../data/raw/data.pkl"
  PORTFOLIO_DATA_FILEPATH: "../data/raw/portfolio.txt"
  METADATA_FILE_PATH: "../data/raw/metadata.csv"
  RESULTS_BASE_DIR: "../data/results"

  # Parameters
  NUM_DAYS_TIME_HORIZON: 180
  ANALYSIS_COLUMN: "Adj Close"
  INVESTMENT_AMOUNT: 1000.  # [$]
  PORTFOLIO_VOLATILITY: 0.06
  SPARSITY_IMPORTANCE: 0.0

  # Plotting
  PRICE_LIMITS: [0.6, 1.4]
  NUM_DAYS_IN_FUTURE: 30
  EXCEEDANCE_PROBABILITY: 0.95